/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as T1IndexRouteImport } from './routes/t1.index'
import { Route as T1BriefingRouteImport } from './routes/t1.briefing'
import { Route as T1Bt19RouteImport } from './routes/t1.bt19'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const T1IndexRoute = T1IndexRouteImport.update({
  id: '/t1/',
  path: '/t1/',
  getParentRoute: () => rootRouteImport,
} as any)
const T1BriefingRoute = T1BriefingRouteImport.update({
  id: '/t1/briefing',
  path: '/t1/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const T1Bt19Route = T1Bt19RouteImport.update({
  id: '/t1/bt19',
  path: '/t1/bt19',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/t1/briefing': typeof T1BriefingRoute
  '/t1/bt19': typeof T1Bt19Route
  '/t1/': typeof T1IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/t1/briefing': typeof T1BriefingRoute
  '/t1/bt19': typeof T1Bt19Route
  '/t1': typeof T1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/t1/briefing': typeof T1BriefingRoute
  '/t1/bt19': typeof T1Bt19Route
  '/t1/': typeof T1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/t1/briefing' | '/t1/bt19' | '/t1/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/t1/briefing' | '/t1/bt19' | '/t1'
  id: '__root__' | '/' | '/t1/briefing' | '/t1/bt19' | '/t1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  T1BriefingRoute: typeof T1BriefingRoute
  T1Bt19Route: typeof T1Bt19Route
  T1IndexRoute: typeof T1IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t1/': {
      id: '/t1/'
      path: '/t1'
      fullPath: '/t1/'
      preLoaderRoute: typeof T1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t1/briefing': {
      id: '/t1/briefing'
      path: '/t1/briefing'
      fullPath: '/t1/briefing'
      preLoaderRoute: typeof T1BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t1/bt19': {
      id: '/t1/bt19'
      path: '/t1/bt19'
      fullPath: '/t1/bt19'
      preLoaderRoute: typeof T1Bt19RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  T1BriefingRoute: T1BriefingRoute,
  T1Bt19Route: T1Bt19Route,
  T1IndexRoute: T1IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
